### ISSUE TITLE
Chart doesn't deploy CRDS when deploying via kustomize

### ISSUE THREAD

**Issue by kubiani** [grafana/alloy-operator#10]
When using Kustomize (i.e. with ArgoCD), this chart doesn't deploy the CRDs. 

```yaml
# kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: https://grafana.github.io/helm-charts
    name: alloy-operator
    version: 0.2.8
    releaseName: alloy-operator
    namespace: alloy-operator
    valuesInline:
      crds: 
        deployAlloyCRD: true
        deployPodLogsCRD: true
```
  
  
Trying to deploy this doesn't pull in the CRDs for deployment:

```bash
kustomize build --enable-helm . | kubectl apply -f - --dry-run=server

serviceaccount/alloy-operator created (server dry run)
role.rbac.authorization.k8s.io/alloy-operator-leader-election-role created (server dry run)
clusterrole.rbac.authorization.k8s.io/alloy-operator-alloy-editor-role created (server dry run)
clusterrole.rbac.authorization.k8s.io/alloy-operator-alloy-viewer-role created (server dry run)
clusterrole.rbac.authorization.k8s.io/alloy-operator-role created (server dry run)
rolebinding.rbac.authorization.k8s.io/alloy-operator-leader-election-rolebinding created (server dry run)
clusterrolebinding.rbac.authorization.k8s.io/alloy-operator-rolebinding created (server dry run)
service/alloy-operator created (server dry run)
deployment.apps/alloy-operator created (server dry run)
```
