### ISSUE TITLE
ClusterRolebinding naming clash when creating instances with equal names in differnet namespaces

### ISSUE THREAD

**Issue by bo0ts** [grafana/alloy-operator#4]
When trying to deploy two instances named "my-alloy" to different namespaces the second instance fails with the following error:

```
  status:
    conditions:
    - lastTransitionTime: "2025-05-06T12:16:06Z"
      status: "True"
      type: Initialized
    - lastTransitionTime: "2025-05-06T12:16:07Z"
      message: 'failed to install release: Unable to continue with install: ClusterRole
        "my-alloy" in namespace "" exists and cannot be imported into the current
        release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace"
        must equal "ns-2": current value is "ns-1"'
      reason: InstallError
      status: "True"
  type: ReleaseFailed
```
